### ISSUE TITLE
Incorrect logic in action generator prevents schema validation

### ISSUE THREAD

**Issue by sbrendtro** [pinknetworkx/atomicassets-js#12]
The actions generator fails validation of correct schemas, and validates incorrect schemas:

**src/Actions/Generator.ts:174**

Instead of checking for NOT exactly equals (this throws the error when key IS in types):
```
        if (typeof types[key] !== 'undefined') {
            throw new SerializationError_1.default('field not defined in schema');
```
Rather it should be exactly equals (will only throw the error when key is NOT in types):
```
        if (typeof types[key] == 'undefined') {
            throw new SerializationError_1.default('field not defined in schema');
```

**Comment by benjaminbours** [comment]
@sbrendtro is completely right. @fabian-emilius is this project still maintained? Is it worth it to spend time opening a PR for this?

**Comment by sbrendtro** [comment]
@benjaminbours from my experience, even if they say they'll merge it, they won't (see pull request #20). Getting them to change or even fix anything is an uphill battle - even when you do the work for them. The problems are systemic, and their chronic unresponsiveness has led me to start this project: https://labs.nftbackers.io/atomicassets-community-api/

**Comment by fabian-emilius** [comment]
Fixed in new version
