### ISSUE TITLE
Action generator needs to translate simplified schema types

### ISSUE THREAD

**Issue by sbrendtro** [pinknetworkx/atomicassets-js#14]
When using action generator on ExplorerApi or RpcApi, the generator passes through the simplified schema types to `immutable_data` and `mutable_data` attribute maps. In most cases this is correct, except for the simplified types. They should instead be translated to their correct underlying types for proper serialization.

For example, if the api.getSchema() endpoint returns:
```
[
  { name: 'name', type: 'string' },
  { name: 'img', type: 'image' },
  { name: 'testint', type: 'uint64' },
  { name: 'testipfs', type: 'ipfs' },
  { name: 'testboolean', type: 'bool' },
  { name: 'testfloat', type: 'double' }
]
```
The generator incorrectly passes through the simplified types into the data:
```
[
  { key: 'name', value: [ 'string', 'Test NFT' ] },
  { key: 'img', value: [ 'image', 'QmXQugyTHjdRv8KD8rFiCtGb585oDwRhtNSrusWxxefJa3' ] },
  {
    key: 'testipfs',
      value: [ 'ipfs', 'QmbMxq17dYSAuNzw8bBrrA8iaEmWpGCM9bLgnihMbJVJnz' ]
  },
  { key: 'testint', value: [ 'uint64', 10 ] },
  { key: 'testboolean', value: [ 'bool', true ] },
  { key: 'testfloat', value: [ 'double', 3.1415 ] }
]
```

Attempting to pass this action data through the eosjs transact() function causes errors:
```
Error: type "image" is not valid for variant
Error: type "ipfs" is not valid for variant
Error: type "bool" is not valid for variant
Error: type "double" is not valid for variant
``` 

One way to accomplish this would be to modify toAttributeMap in the action generator (src/Actions/Generator.ts:164).
```
export function toAttributeMap(obj: any, schema: SchemaFormat): AttributeMap {
    // A translation map from simplified types to their underlying attribute types
    const translation = {
        image: 'string',
        ipfs: 'string',
        bool: 'uint8',
        double: 'float64'
    };
    const types: { [id: string]: string } = {};
    const result: AttributeMap = [];

    for (const row of schema) {
        types[row.name] = row.type;
    }

    const keys = Object.keys(obj);
    for (const key of keys) {
        if (typeof types[key] == 'undefined') { /* NOTE this includes the logic fix from #12 */
            throw new SerializationError('field not defined in schema');
        }
        // Ensure int value for bool type
        if ( types[key] == 'bool' ) {
            obj[key] = obj[key] | 0;
        }
        // Translate simplified schema types
        let keytype = types[key];
        if ( translation[keytype] ) {
            keytype = translation[keytype];
        }

        result.push({key, value: [types[key], obj[key]]});
    }

    return result;
}
```

**Comment by fabian-emilius** [comment]
The attribute map is does not have the same types like in the schema. The attribute map is a representation of a C++ struct so it only understands C++ types

**Comment by sbrendtro** [comment]
I think you missed the point of the issue. I realize the attribute map uses the C++ types. The problem is the action generator reuires that you only pass in the low level C++ types, rather than the high level ones commonly used on sites. Users of the JS API are getting back high level types from places like getSchema(), so it stands to reason they should be able to use them in places like the action generator without having to understand the low-level representation in the contract. The API should be consistent.... and right now it's not.

**Comment by fabian-emilius** [comment]
yes now I get it. Thank you this will be fixed in the next version
